---
- hosts: sverka-03
  sudo: yes
  roles:
  - role: etckeeper
  - role: common-utils
  - role: graphite-carbon
  - role: graphite-api
  - role: collectd
  - role: grafana-dockerized
  - role: grafana-container
  - role: prometheus-container
  - role: graphite-exporter-container

- hosts: all
  sudo: yes
  roles:
  - role: collectd
